name: CI SynoSDK

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      SYNO_MAIN_VERSION: 7.1.1
      SYNO_VERSION: 42962

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
            ref: main
            path: './repo'
       
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
            version: latest
            platform: x64

      - name: Compile
        working-directory: ./repo/src
        run: |
            gcc -s -fPIC -shared -o prelibsynophoto.so prelibsynophoto.c
            gcc -s -fPIC -shared -o prelibsynosdk.so prelibsynosdk.c
            strip -s prelibsynophoto.so
            strip -s prelibsynosdk.so
            mv prelibsynophoto.so x86/prelibsynophoto.so
            mv prelibsynosdk.so x86/prelibsynosdk.so
            cd ../../
            cp -r ./repo ./repoPatch
            
      - name: Patch
        run: |
            cd repoPatch
            sudo chmod -R 777 ./
            cd lazy
            sudo ./auto_patch_SynoSDK.sh "DS920+" "${SYNO_MAIN_VERSION}" "${SYNO_VERSION}"   
            cd ../../
            sudo cp -v ./repoPatch/libsynosdk.so.7 ./repo/libsynosdk.so.7
      
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Synology V${{env.SYNO_VERSION}}"
          repository: './repo'
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PreloadLibrary
          path: ./repo/src/x86/*.so
          if-no-files-found: error        
              
      - name: Delete old workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          body: "Synology V${{ env.SYNO_VERSION }} only"
          name: "Patch SYNO V${{ env.SYNO_VERSION }}"
          tag_name: "${{ env.SYNO_VERSION }}"
          files: |
            ./repo/libsynosdk.so.7